// LOCALHOST
### Get all contacts
GET http://localhost:3000/users

### Get contacts by Id
GET http://localhost:3000/users/67cc93afb1ee6363677edad9

### Create contact
POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{
    "email": "test1@test.com",
    "birthday": "05-08-1994",
    "favoriteColor": "Blue",
    "firstName": "Nico",
    "lastName": "Uro"
}

### Update contact
PUT http://localhost:3000/users/67d48aacebab7a6fc54f93ad HTTP/1.1
Content-Type: application/json

{
    "email": "test1@test.com",
    "birthday": "05-08-1994",
    "favoriteColor": "Blue",
    "firstName": "Nico",
    "lastName": "Uro"
}

### Delete contact
DELETE  http://localhost:3000/users/67d6f18ffb35b01afaa82aca HTTP/1.1
