// LOCALHOST
### Get all contacts
GET http://localhost:8080/personalinfo

### Get contacts by Id
GET http://localhost:8080/personalinfo/67e052e2306a0d6fe431dc7b

### Create contact
POST http://localhost:8080/personalinfo HTTP/1.1
Content-Type: application/json

{
    "firstName": "Alex",
    "lastName": "Uro",
    "email": "uronico3@gmail.com",
    "address": "245 Santa Maria, Laguna, Philippines 4022",
    "phoneNumber": "09505358336",
    "bookTitle": "Book Title",
    "authorName": "Author Name",
    "borrowerName": "Borrower Name",
    "dateBorrowed": "2023-01-01",
    "dateReturn": "2023-01-15",
    "librarian": "Librarian Name"
}

### Update contact
PUT http://localhost:8080/personalinfo/67e3082006d35b53332127a7 HTTP/1.1
Content-Type: application/json

{
    "firstName": "Gary",
    "lastName": "Uro",
    "email": "uronico3@gmail.com",
    "address": "245 Santa Maria, Laguna, Philippines 4022",
    "phoneNumber": "09505358336",
    "bookTitle": "Book Title",
    "authorName": "Author Name",
    "borrowerName": "Borrower Name",
    "dateBorrowed": "2023-01-01",
    "dateReturn": "2023-01-15",
    "librarian": "Librarian Name"
}

### Delete contact
DELETE http://localhost:8080/personalinfo/67e3082006d35b53332127a7 HTTP/1.1